name: Build Zephyr Application Image
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zephyr-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: ghcr.io/zephyrproject-rtos/ci:0.26.6
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: West build
        run: west build