name: Build Zephyr Application Image
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zephyr-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: zephyrprojectrtos/ci:v0.26.6
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    timeout-minutes: 10
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: megabit-coproc

      - name: init workspace
        working-directory: megabit-coproc
        run: |
          west init
          west update -o=--depth=1 -n

      - name: cmake configuration
        working-directory: megabit-coproc
        run: cmake -Bbuild -GNinja

      - name: build firmware application image
        working-directory: megabit-coproc
        run: ninja -Cbuild